# Generated by Django 4.2.10 on 2024-03-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstats',
            name='score_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentstats',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
