# Generated by Django 4.2.10 on 2024-03-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_created_by_category_is_active'),
        ('users', '0005_studentstats_score_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstats',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.category'),
        ),
        migrations.AlterField(
            model_name='studentstats',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.subcategory'),
        ),
    ]
