# Generated by Django 4.2.10 on 2024-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentstats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstats',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
