# Generated by Django 4.2.10 on 2024-03-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_studentstats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstats',
            name='is_enabled',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=200),
        ),
    ]
