# Generated by Django 4.2.10 on 2024-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_studentstats_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstats',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
