# Generated by Django 4.2.11 on 2024-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_studentstats_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstats',
            name='is_enabled',
            field=models.CharField(default='disabled', max_length=100),
        ),
    ]
