# Generated by Django 5.0.2 on 2024-03-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_studentstats_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstats',
            unique_together=set(),
        ),
    ]
