# Generated by Django 4.2.10 on 2024-03-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_studentstats_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstats',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentstats',
            name='creation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
