# Generated by Django 4.2.10 on 2024-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_studentstats_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstats',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='studentstats',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='studentstats',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
