# Generated by Django 4.2.11 on 2024-03-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_studentstats_is_enabled'),
        ('users', '0018_remove_studentstats_creation_date_and_more'),
    ]

    operations = [
    ]
