# Generated by Django 4.2.10 on 2024-03-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_created_by_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
