# Generated by Django 4.2.10 on 2024-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
