# Generated by Django 4.2.10 on 2024-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_quizattempt_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='disabled_css',
            field=models.CharField(default='disabled', max_length=200),
        ),
    ]
