# Generated by Django 5.0.2 on 2024-03-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_subcategory_is_active_alter_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_style',
            field=models.CharField(default='disabled', max_length=50),
        ),
    ]
