# Generated by Django 5.0.2 on 2024-03-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_subcategory_is_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='is_style',
        ),
    ]
