# Generated by Django 4.2.10 on 2024-03-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_subcategory_is_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='creation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
