# Generated by Django 4.2.10 on 2024-03-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_subcategory_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='creation_date',
            new_name='exam_date',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='creation_time',
            new_name='exam_time',
        ),
    ]
