# Generated by Django 4.2.11 on 2024-03-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_rename_creation_date_subcategory_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
