# Generated by Django 4.2.11 on 2024-03-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
    ]
