# Generated by Django 4.2.11 on 2024-03-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_question_photo_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='photo_main',
        ),
    ]
