# Generated by Django 4.2.11 on 2024-03-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_question_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
